### ISSUE TITLE
yaml file for plot_training in unsuitable format

### ISSUE THREAD

**Issue by clessig** [ecmwf/WeatherGenerator#290]
### Is your feature request related to a problem? Please describe.

The YAML file 

```
train:
   plot:
    - run_ids: [abcde, fghij]
    - job_ids: [123456, 654321]
    - experiment_names: [experiment1, experiment2]
```

This is error prone since the per run information needs to be entered i three lines. It can also become cluttered with many runs, and it's not easy to comment out an individual run. 

### Describe the solution you'd like

The format should be

```
train:
   plot:
    - abcde : [123456, 'description 1']
    - abcdf : [123457, 'description 2']
    - ...
```
